// <auto-generated>
// Automatically generated by the tool, do not modify
// </auto-generated>

using System.Diagnostics;
using UIFramework.Runtime;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace UI.TestOne
{
    public class TestOneUI : BaseUI
    {
        public RectTransform TitleTrans;
        public TextMeshProUGUI TitleTmp;
        public GameObject TitleGo;
        public RectTransform IconTrans;
        public Image IconImg;
        public GameObject IconGo;
        public RectTransform ChangedBtnTrans;
        public Image ChangedBtnImg;
        public Button ChangedBtnBtn;
        public GameObject ChangedBtnGo;

        [Conditional("UNITY_EDITOR")]
        private void BindComponent()
        {
            Canvas = GetComponent<Canvas>();
            Raycaster = GetComponent<GraphicRaycaster>();
            Content = transform.Find("Content") as RectTransform;
            BlackImage = GetComponent<Image>();
            Raycast = transform.Find("Raycast").GetComponent<UIRaycast>();
        
            var Title = transform.Find("Content/Title");
            var Icon = transform.Find("Content/Icon");
            var ChangedBtn = transform.Find("Content/ChangedBtn");
        
            TitleTrans = Title.GetComponent<RectTransform>();
            TitleTmp = Title.GetComponent<TextMeshProUGUI>();
            TitleGo = Title.gameObject;
            IconTrans = Icon.GetComponent<RectTransform>();
            IconImg = Icon.GetComponent<Image>();
            IconGo = Icon.gameObject;
            ChangedBtnTrans = ChangedBtn.GetComponent<RectTransform>();
            ChangedBtnImg = ChangedBtn.GetComponent<Image>();
            ChangedBtnBtn = ChangedBtn.GetComponent<Button>();
            ChangedBtnGo = ChangedBtn.gameObject;
        }
    }
}