// <auto-generated>
// 通过模版自动生成，仅允许手动删除 AddInfo 项以修复编译错误。
// </auto-generated>

using System;
using UI.Core;
using UI.Page;
using UIFramework.Runtime.InfoContainer;

namespace UI.Core
{
    public partial class UIManager
    {
        private void AddInfo(UIType uiType, UILayer layer, Type pageType, string loadPath)
        {
            InfoContainer.AddInfo(new UIInfo(pageType, (int)layer, loadPath));
        }
        
        private void LoadInfos()
        {
            AddInfo(UIType.TestOne, UILayer.Dialog, typeof(TestOnePage), "TestOneUI");
            AddInfo(UIType.TestTwo, UILayer.Dialog, typeof(TestTwoPage), "TestTwoUI");
            AddInfo(UIType.TestThree, UILayer.Dialog, typeof(TestThreePage), "TestThreeUI");
        }
    }
}